### ISSUE TITLE
Wrong watcher name in logs

### ISSUE THREAD

**Issue by bleuchtang** [Vadims06/ospfwatcher#16]
Even if I set a watcher name in watcher configuration like this:

```
topology:
  defaults:
    labels:
      watcher_name: ospf
```

Name in logs will still is watcher-local:
```
2024-11-20T13:46:27Z,watcher-local,network,IP/32,changed,old_cost:200,new_cost:-1,IP,20Nov2024_09h41m50s_502_hosts,,,external,1
```

PS: This issue is not present in isis watcher

**Comment by Vadims06** [comment]
Hi Emile,
I generated new watcher config, started a lab and it looks like it uses the name from configuration file
```
2024-12-02T13:26:10Z,ospf1,metric,10.10.10.3,changed,old_cost:22,new_cost:222,10.10.10.2,,0.0.0.0,12345
2024-12-02T13:26:10Z,ospf1,network,192.168.23.0/24,changed,old_cost:22,new_cost:222,10.10.10.2,,0.0.0.0,12345,internal,0
```
my configuration file
```
  nodes:
    ospf-watcher:
      kind: linux
      image: vadims06/ospf-watcher:latest
      network-mode: container:router
      startup-delay: 10
      env:
        ASN: '12345'
        WATCHER_NAME: ospf1
        AREA_NUM: 0.0.0.0
        WATCHER_INTERFACE: veth1
        WATCHER_LOGFILE: /home/watcher/watcher/logs/watcher.log
```
Please check if `WATCHER_NAME` exist in your configuration file or remove `ospfwatcher/watcher/watcher<num>-gre<gre_num>-ospf`, fetch fresh updates via `git pull` and regenerate watcher's config one more time. Let me know if it works
